### PR TITLE
Update deprecated deal.II function

### PR DESCRIPTION
**Pull request by DavidSCN**
That's a bit awkward, a few weeks before the deal.II release, the function `extract_boundary_dofs` has been deprecated and changed from return by argument to return by value. This change is not backward compatible, but every build here triggers now a series of deprecated warnings. 
I'm a bit attempted to drop an adapter release with deal.II v9.3 (release soon) and merge this PR afterwards. Otherwise we force everyone to use a deal.II develop version. Alternative opinions welcome.

### CODE REVIEW

**Comment by uekerman** [comment]
Why not merging this now?
I guess we want that our develop is always compatible with the deal.II develop and our latest release should be compatible with the latest release of deal.II. Right?

**Comment by DavidSCN** [comment]
Backward compatibility for deal.II was quite a big thing in the past. deal.II provides packages for some distributions and they make the installation for many people much easier. Of course, we should merge here, but I would still drop a backward compatible release of the current state.

**Comment by DavidSCN** [comment]
Yes, I would drop a release branch together with the release package. However, I would not further maintain the release branch/ the release itself. It is supposed to be a snapshot of the current state.

**Comment by DavidSCN** [comment]
Proposed method: 
- (1) Create a release branch and a GitHub release indicating compatible versions: `v0.1-deal.IIv9.1` 
- (2) increase the required version here to deal.II v10 and merge this commit

**Comment by DavidSCN** [comment]
I selected now an alternative without the releasing by simply using deal.II macros. Since our adapter is currently unstable with the latest deal.II release, let me directly merge.

**Pull request merged**
