### PR TITLE
Link source objects against preCICE

### PR DESCRIPTION
**Pull request by DavidSCN**
In #60 I introduced an issue regarding the linking of the object files. The current changes revert some of the changes there so that everything works on my system as expected. However, IIRC we could not do this in the current way as the linked object are actually object files and older cmake versions complained something like: you cannot link against object files. I need to find the native CMake syntax here or increase the minimum required CMaker version . @fsimonis any ideas?

### CODE REVIEW

**Comment by DavidSCN** [comment]
Problem is a bit that I cannot really reproduce the CMake version 3.10 behavior since the LRZ cluster removed the version and I am not very eager to install cmake on my local system. I propose to just increase the minimum required cmake version to 3.13 and go with this changes here.

**Comment by uekerman** [comment]
The cmake version we require in preCICE is 3.10, diverging here could lead to problems in the long run.
With a virtual machine or docker this should be easy to test, no?

**Comment by fsimonis** [comment]
Our minimum versions is `3.10` as we still want to support `Ubuntu 18.04 LTS`, which is [3.10.2](https://pkgs.org/search/?q=cmake)

**Comment by DavidSCN** [comment]
Solved it now, but in a different way, requirements should be ok by now.

**Pull request merged**
